### ISSUE TITLE
Quite a few issues on curseforge.

### ISSUE THREAD

**Issue by drakosoldier298** [TheMindVirus/CC-Modded#7]
First thing, Wrong licensing, You have it set to MIT the correct licensing would be ccpl.

Second, please make new screenshots I can't see very well with nighttime screenshots due to your textures being darker colours.

And in your comment's you mention this being a fork of cc:tweaked however you do not mention this anywhere else. Unless you count one line saying "CC:TWEAKED Tweaked some more." It would be good to have a link to tweaked as well.

Finally, please use Github's release feature instead of having a build folder.

**Comment by TheMindVirus** [comment]
First thing, come back to this in ten years when 10+ new licenses would have been invented to elongate the lifespan of a 10 year old piece of software, then say MIT is the wrong license to me again.

Second, why don't you take better screenshots then? I've given you the resources to do so and so have the original mod authors. I have issue with curseforge being light and no dark.

There is a GitHub official fork and an unofficial GitHub fork of which seems to be receiving more attention and development, and it also seems to be how people are actually working now, through private contributions because pull requests get ignored.

Finally, on platforms which aren't GitHub, when you clone the repository you only get a development snapshot and lose all releases so it makes migration a big problem, especially when taking into account submodules which I also don't use.

Please rethink your stance from the developer's perspective before criticising repositories.

**Comment by Merith-TK** [comment]
Please rethink your stance from someone who is just having some accessibility issues and is confused about some choices made.

And the License is *legally* required unfortunately, at the very least please dont mark the mod as MIT on curseforge,

**Comment by TheMindVirus** [comment]
I question the legality of a license that does not appear to be on the list of available licenses,
There is the option of custom license but anyone can copy and paste that, so an applicable license has been selected in its place to match a large number of educationally licensed repositories. There's nothing wrong there.

My stance has been carefully considered and is not changing, nor is there any intent to argue against someone having accessibility issues. The original poster seems perfectly capable of sorting this out for themselves and I have even provided a compatibility view on curseforge, but still you insist on attacking me. I do not favour this approach.
